---
- stat:
    path: "{{ nginx_includes_templates_path }}"
  become: false
  delegate_to: localhost
  register: nginx_includes_local_directory

- block:
  - name: Build list of Nginx includes templates for Laravel
    find:
      paths: "{{ nginx_includes_templates_path }}"
      pattern: "*.conf.j2"
      recurse: yes
    become: false
    delegate_to: localhost
    register: nginx_includes_templates

  - name: Create includes.d directories for Laravel
    file:
      path: "{{ nginx_path }}/includes.d/{{ item }}"
      state: directory
      recurse: yes
      mode: '0755'
    loop: "{{ nginx_includes_templates.files | map(attribute='path') |
                    map('regex_replace', nginx_includes_pattern, '\\2') |
                    map('dirname') | unique | list | sort
                 }}"
    when: nginx_includes_templates.files | count

  - name: Template files out to includes.d for Laravel
    template:
      src: "{{ item }}"
      dest: "{{ nginx_path }}/includes.d/{{ item | regex_replace(nginx_includes_pattern, '\\2') }}"
      mode: '0644'
    loop: "{{ nginx_includes_templates.files | map(attribute='path') | list | sort(True) }}"
    notify: reload nginx
  when: nginx_includes_local_directory.stat.isdir is defined